config/routes.rb
require "sidekiq/web"

Shakhak::Application.routes.draw do

  get "filter/categories"
  get "filter/" => "filter#index"
  get "dashboard" => "dashboard#index", :as => :dashboard_index

  scope "dashboard" do
    resources :categories
    resources :advertises do
      member do
        get "renew"
        patch "do_renew"
        delete "renew/:renew_id/", :action => :destroy_renew, :as => :delete_renew
      end

    end
  end

  get "/auth/:provider/callback" => "services#create"

  resources :services, only: [:index, :destory]

  devise_for :users, controllers: {registrations: "registrations"}

  mount Sidekiq::Web, :at => "/admin/sidekiq"
  root to: 'home#index'
  get "/advertises" => "home#advertises", :as => "global_advertises"

end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
  layout "dashboard"

  before_action :set_advertise, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /advertises
  # GET /advertises.json
  def index
    @advertises = current_user.advertises.page(params[:page])
    respond_to do |format|
        format.html
        format.json
    end
  end

  # GET /advertises/1
  # GET /advertises/1.json
  def show
  end

  # GET /advertises/new
  def new
    @categories = Category.all
    @advertise = Advertise.new
    @advertise.user = current_user
  end

  # GET /advertise/1/renew
  def renew
    begin
      @advertise = current_user.advertises.find(params[:id])
      @advertise.show_for_days = 0
      @advertise.cost = 0
    rescue ActiveRecord::RecordNotFound
      not_found
    end

  end

  def do_renew

    @advertise = current_user.advertises.find_by_id(params[:id].to_i)
    if not @advertise then not_found end

    renew = Renew.where(:advertise_id => @advertise.id).order("renew_date desc").limit(1).select("renew_date, show_for_days")

    if not renew.empty?
      # Retrieve the last renew scheduled date
      last_renew = renew[0].renew_date
      last_renew_show_for_days = renew[0].show_for_days
      last_renew_date = last_renew + last_renew_show_for_days.days

    else
      last_renew_date = @advertise.deactive_date

    end

    # schedule the renew worker to run at the last expiration date
    jid = RenewWorker.perform_at(last_renew_date,
                                 {:id => params[:id]}.update(params.require(:advertise).permit(:cost,
                                                                                               :show_for_days)), 1)
    # Save the renew record to database so we can look back
    # and cancel them if user want
    renew = Renew.new(:user => current_user,
                      :advertise => @advertise,
                      :renew_date => last_renew_date,
                      :show_for_days => params[:advertise][:show_for_days],
                      :cost => params[:advertise][:cost],
                      :jid => jid)
    renew.save


    flash[:notice] = _("your renew order scheduled")
    redirect_to :dashboard_index
  end

  # GET /advertises/1/edit
  def edit
    @categories = Category.all
  end

  # POST /advertises
  # POST /advertises.json
  def create
    @advertise = Advertise.new(advertise_params)
    @advertise.user = current_user

    respond_to do |format|
      if @advertise.save

        Log.create(:logable => @advertise, :user => current_user,
                   :msg => _("new advertise \#%{id} created") % {:id => @advertise.id, asdasD: "Asd"})

        format.html { redirect_to target_url || @advertise, notice: 'Advertise was successfully created.' }
        format.json { render action: 'show', status: :created, location: @advertise }
      else
        @categories = Category.all
        format.html { render action: 'new' }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertises/1
  # PATCH/PUT /advertises/1.json
  def update
    respond_to do |format|
      if @advertise.user == current_user

        if @advertise.update(advertise_params)
          Log.create(:logable => @advertise, :user => current_user,
                     :msg => _("\#%{id} advertise updated") % {:id => @advertise.id})
                     #:changes => @advertise.changes))

          format.html { redirect_to target_url || @advertise, notice: 'Advertise was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @advertise.errors, status: :unprocessable_entity }
        end
      else
        return forbidden
      end
    end
  end

  # DELETE /advertises/1
  # DELETE /advertises/1.json
  def destroy
    if @advertise.user == current_user
      # BUG: Log entry should contains the removed advertise
      #      id even after its removal.
      Log.create(:user => current_user,
                 :msg => _("advertise deleted", :id => @advertise.id))

      @advertise.destroy
   else
      return forbidden
    end

    respond_to do |format|
      format.html { redirect_to target_url || advertises_url }
      format.json { head :no_content }
    end
  end

  # DELETE /advertises/1/renew/1
  # DELETE /advertises/renew/1.json
  def destroy_renew
    @renew = Renew.find_by_id(params[:renew_id].to_i)
    if not @renew then not_found end

    @advertise = Advertise.find_by_id(params[:id].to_i)
    if not @advertise then not_found end

    if @renew.user != current_user or @renew.advertise != @advertise
      forbidden
    end

    Log.create(:user => current_user,
               :msg => _("renew deleted", :id => @advertise.id,
                         :renew_id => @renew.id))

    # Delete the scheduled job
    queue = Sidekiq::ScheduledSet.new
    renew_job = queue.find_job(@renew.jid)
    if renew_job
      renew_job.delete
    end

    @renew.destroy

    flash[:notice] = _("renew removed")
    redirect_to :dashboard_index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertise
      @advertise = Advertise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertise_params
      params.require(:advertise).permit(:title, :description,
                                        :show_for_days, :cost,
                                        :size, :category_id, :tag_list)
    end

    private

    def forbidden
      render text: "You don't have access to this resource", status: :forbidden
    end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/views/advertises/_form.html.erb
<%= semantic_form_for @advertise, :validate => true do |f| %>
  <%= f.inputs :name => _("Basic Information") do %>
    <p><%= _("basic information description") %></p>
    <div class="row">
      <div class="small-12 columns">
	<div class="row">
	  <div class="small-6 columns">
	    <%= f.input :title, :label => _("Title"), :placeholder => _("Title of your advertise") + " ..."  %>
	  </div>

	  <div class="small-6 columns">
	    <div class="custom dropdown">
	      <%= f.input :category, :label => _("Category"), :class => "medium", :placeholder => _("category") + " ..." %>

	    </div>
	  </div>
 	</div>
      </div>
    </div>
  <% end %>

  <%= f.inputs :name => _("Cost Related Information") do %>

    <p><%= _("Cost related informations description") %></p>
    <div class="row">

      <div class="small-6 columns">
	<%= f.input :show_for_days, :label => _("Show for days"), :placeholder => _("for example: 4") + " ..." %>
      </div>
      <div class="large-6 columns">
	<%= f.input :cost, :label => _("Cost"), :placeholder => _("for example 45000") + " ..." %>
      </div>
    </div>

    <div class="row">
      <div class="large-6 columns">
	<%= f.input :size, :label => _("Size"), :as => :select, :collection => Advertise::SIZES.collect {|k,v| [v, k]} %>
      </div>
    </div>
  <% end %>

  <%= f.inputs :name => _("Details") do %>

    <p><%= _("details description") %></p>
    <div class="row">
      <div class="large-6 columns">
	<%= f.input :tag_list, :label => _("Tags"), :placeholder => _("Use ',' as separator").html_safe + " ..." %>
      </div>
      <div class="large-6 columns">
	<%= f.input :picture, :label => _("Image"), :placeholder => _("Picture") + " ..." %>
      </div>
    </div>
    <br />
    <div class="row">
      <div class="large-12 columns">
	<%= f.input :description, :label => _("Description"), :placeholder => _("Complete description of you advertise") + " ..." %>
      </div>
    </div>

  <% end %>

  <div id="wizardbuttons" class="row actions ">
    <button id="preview" class="button red small"><%= _("Preview") %></button>
    <%= f.submit :class => "button success small" %>
  </div>

<% end %>

app/views/advertises/edit.html.erb
<h1><%= _("Editing advertise") %></h1>

<%= render 'form' %>

<%= link_to _('Show'), @advertise, class: show_btn_class, icons: show_btn_icon %>
<% if session[:dashboard] %>
  <%= link_to 'Back', dashboard_index_path, class: back_btn_class, icons: back_btn_icon  %>
<% else %>
  <%= link_to 'Back', advertises_path,  class: back_btn_class, icons: back_btn_icon  %>
<% end -%>

app/views/advertises/index.html.erb
<h1><%= _("Listing advertises") %></h1>
<div class="row dashbody">

  <div class="row">
    <div class="small-12 columns large-12">
      <% if not @advertises.empty? %>
	<div class="table-list advertise-list span12">
	  <ul>
	    <% @advertises.each do |advertise| %>
	      <li>
		<div class="inline right">
                  <a href="javascript:void(0);" class="dashboard-show-overload">
                    <%= advertise.title %>
                  </a>
                </div>
		<div class="inline left">
		  <%= link_to '', advertise, method: :delete, data: { confirm: 'Are you sure?'}, class: del_btn_class, icons: del_btn_icon %>
		</div>
		<div class="inline left">
		  <%= link_to "", edit_advertise_path(advertise), class: edit_btn_class, icons: edit_btn_icon %>
		</div>
                <div class="overload">
                  Some text comes here
                </div>
	      </li>
	    <% end %>
	  </ul>

	</div>
        <%= paginate @advertises %>

      <% end %>

    </div>

  </div>
</div>

app/views/advertises/new.html.erb
<%= content_for :sidebar do %>
  <div class="hide-for-small large-3 columns ">
    <%= render "dashboard/sidemenu" %>
    <br />
    <div class="row">
      <div id="es-cost-per-day" data-warning="1000"  data-danger="500" class="simulator box-noproblem  large-11 columns panel ">
        <h1>0</h1>
        <span><%= _('cost per day') %></span>
      </div>
    </div>

    <div class="row">
      <div id="es-credit" data-warning="10000" data-danger="5000" class="simulator large-11 box-noproblem columns panel ">
        <h1>0</h1>
        <span><%= _('credit') %></span>
      </div>
    </div>

    <div class="row">
      <div id="es-cost" data-warning="10000" data-danger="5000" class="simulator large-11 box-noproblem columns panel">
        <h1>0</h1>
        <span><%= _('cost') %></span>
      </div>
    </div>

  </div>
  <div class="small-12 large-9 columns">

<% end %>

<div class="row">

  <div class="small-12 columns">
    <%= link_to _("Back"), advertises_path, class: back_btn_class, icons: back_btn_icon %>
  </div>

  <div id="newadvertise">
    <div id="wizard" class="row" data-next="<%= _("Next") %> <i class='icon-chevron-left'></i>" data-prev="<i class='icon-chevron-right'></i> <%= _("Prev") %>" data-btnclass="button small secondary" data-steps-name="<%= _("Step") %>">
      <div class="small-12 columns">

	<%= render 'form' %>
      </div>
    </div>
  </div>

  <div id="adpreview" class="ad-preview hide">
    <div class="row">
      <div class="small-12 columns">
	<button id="backtowizard" class="btn secondary small"><%= _("Back to wizard") %></button>
      </div>
    </div>

    <div id="preview-container"class="row"><div class="small-12 columns">

        <!-- adbox -->
        <div id="previewad" class="box box1x1" data-container-class="bannercontainers">
	  <div id="innerbox">
	    <h1 class="title"></h1>
	  </div>

          <div id="banner" class="bottombanner">

            <div class="ad-info bannercontainers">
              <div><span><i  data-tip="likes" class="icon-thumbs-up"></i> 494</span></div>
              <div><span><i  data-tip="views" class="icon-eye-open"></i> 3,000</span></div>
            </div>
	    <div class="iconsection">
	      <ul>
	        <li id="preview-category-id" class="category" data-tip="<%= _('category') %>"><i class="icon-sitemap"></i></li>
	        <li id="preview-tag" class="tag" data-tip="<%= _('tags list') %>"><i class="icon-tag"></i></li>
	        <!--<li class="user"><i class="icon-user"></i></li>-->
	        <li class="filter" data-tip="<%= _("Filter similar advertises") %>"><i class="icon-filter"></i></li>
	      </ul>
	    </div>
	  </div>

	</div>
        <!-- addbox -->

      </div>
    </div>

  </div>
</div>

app/views/advertises/renew.html.erb
<h1><%= @advertise.title %></h1>

<%= form_for @advertise, url: {action: :do_renew} do |f| %>
  <div class="field">
    <%= f.label  _("show for days") %><br/>
    <%= f.text_field :show_for_days %>
  </div>
  <div class="field">
    <%= f.label _("cost") %><br/>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= submit_tag _("Renew"), class: add_btn_class, icons: "icon-ok" %>
  </div>

<% end %>

app/views/advertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= _("title") %>:</strong>
  <%= @advertise.title %>
</p>

<p>
  <strong><%= _("category") %>:</strong>
  <%= @advertise.category.name %>
</p>
<p>
  <strong><%= _("show for days") %>:</strong>
  <%= @advertise.show_for_days %>
</p>

<p>
  <strong><%= _("cost") %>:</strong>
  <%= @advertise.cost %>
</p>

<p>
  <strong><%= _("size") %>:</strong>
  <%= @advertise.get_size %>
</p>
<p>
  <strong><%= _("cost per day") %>:</strong>
  <%= @advertise.cost_per_day %>
</p>
<p>
  <strong><%= _("deactive date") %>:</strong>
  <%= @advertise.deactive_date %>
</p>


<p>
  <strong><%= _("description") %>:</strong>
  <%= @advertise.description %>
</p>

<%= link_to _("Renew"), renew_advertise_url, class: "btn btn-success", icons: "icon-ok" %>
<%= link_to _('Edit'), edit_advertise_path(@advertise), class: edit_btn_class, icons: edit_btn_icon %>
<% if session[:dashboard] %>
  <%= link_to _('Back'), dashboard_index_path, class: back_btn_class, icons: back_btn_icon %>
<% else %>
  <%= link_to _('Back'), advertises_path, class: back_btn_class, icons: back_btn_icon %>
<% end -%>