config/routes.rb
require "sidekiq/web"

Shakhak::Application.routes.draw do

  get "filter/categories"
  get "filter/" => "filter#index"
  get "dashboard" => "dashboard#index", :as => :dashboard_index

  scope "dashboard" do
    resources :categories
    resources :advertises do
      member do
        get "renew"
        patch "do_renew"
        delete "renew/:renew_id/", :action => :destroy_renew, :as => :delete_renew
      end

    end
  end

  get "/auth/:provider/callback" => "services#create"

  resources :services, only: [:index, :destory]

  devise_for :users, controllers: {registrations: "registrations"}

  mount Sidekiq::Web, :at => "/admin/sidekiq"
  root to: 'home#index'
  get "/advertises" => "home#advertises", :as => "global_advertises"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    session[:dashboard] = true
    @advertises = current_user.advertises.order("updated_at").page(params[:page]).per(15)
    #@advertises = Advertise.where(user: current_user).order("updated_at").page(params[:page])
    @renew_records = current_user.renews.order("renew_date desc").limit(20)
    @logs = current_user.logs.order("created_at DESC").limit(20)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def remainingDaysClass(days)
    if days < Rails.application.config.advertise_warning_limit
      return "warning"
    elsif days < 1
      return "error"
    end
  end
end

app/views/dashboard/_navbar.html.erb
<header>
    <nav>
      <div class="logo">
	<h1><a href="<%= root_url %>"><span><%=_("Shakhak")%></span></a></h1>
      </div>

      <ul class="pull-right">
	<li data-textip="asdasdasd" data-my="top center" data-at="bottom center">
	  <a href="<%= root_url %>"><i class="icon-home"></i> <%=t :home %></a>
	</li>
	<li>
	  <a href="<%= dashboard_index_url %>"><i class="icon-th-large"></i> <%=t :dashboard %></a>
	</li>

      </ul>

      <ul class="pull-left">
	<li>
	  <a href="<%= root_url %>"><i class="icon-cog icon-large"></i></a>
	</li>

      </ul>

    </nav>
</header>

app/views/dashboard/_sidemenu.html.erb
<div class="row">
  <aside class="sidemenu large-11 columns">
    <div class="row">
    <div class="menuheader small-12 columns">
      <%= _("credit") %>: <span id="credit">40000</span> B
    </div>
    </div>

    <ul class="menu row">
      <li class="small-12 columns"><a href="<%=  advertises_path %>"><i class="icon-inbox icon-large"></i> <%= _("advertises") %></a></li>
      <% if can? :manage, Category %>
	<li class="small-12 columns"><a href="<%=  categories_path %>"><i class="icon-sitemap icon-large"></i> <%= _("category") %></a></li>
      <% end %>

      <% if can? :manage, User %>
	<li class="small-12 columns"><a href="#"><i class="icon-group icon-large"></i> <%= _("users") %></a></li>
      <% end %>

      <li class="small-12 columns"><a href="#"><i class="icon-user icon-large"></i> <%= _("profile") %></a></li>
      <li class="small-12 columns"><a href="<%=  destroy_user_session_path %>" data-method="delete"><i class="icon-signout icon-large"></i> <%= _("log_out") %></a></li>

    </ul>
  </aside>
</div>

app/views/dashboard/index.html.erb
<div class="row dashbody">

  <div class="large-12 small-12 columns">
    <div class="section-container tabs" data-section>
      <section>
	<p class="title" data-section-title><a href="#panel1"><%= _("Advertises") %></a></p>
	<div class="content" data-section-content>


	  <div class="row">
	    <div class="small-12 columns large-9">
	      <%= link_to _("New advertise"), new_advertise_path,  class: add_btn_class + " small", icons: add_btn_icon %>
	    </div>
	  </div>
	  <div class="row">
	    <div class="small-12 columns large-12">
	      <% if not @advertises.empty? %>
		<div class="table-list advertise-list span12">
		  <ul>
		    <% @advertises.each do |advertise| %>
		      <li>
			<div class="inline right">
                          <a href="javascript:void(0);" class="dashboard-show-overload">
                            <span class="<%= remainingDaysClass advertise.remaining_days %>">
                            <%= advertise.title %>
                            </span>
                          </a>
                        </div>
			<div class="inline left">
			  <%= link_to '', advertise, method: :delete, data: { confirm: 'Are you sure?'}, class: del_btn_class, icons: del_btn_icon %>
			</div>
			<div class="inline left">
			  <%= link_to "", edit_advertise_path(advertise), class: edit_btn_class, icons: edit_btn_icon %>
			</div>
                        <div class="overload">
                          Some text comes here
                        </div>
		      </li>
		    <% end %>
		  </ul>

	      </div>
<%= paginate @advertises %>

<% end %>

</div>




</section>
<section>
  <p class="title" data-section-title><a href="#panel-renews"><%= _("Renews") %></a></p>
  <div class="content" data-section-content>

    <div class="row">
      <% if @renew_records.exists? %>
	<p><%= _("latest renews") %></p>
	<table class="span12 table table-striped">
	  <thead>
	    <th><%= _("created at") %></th>
	    <th><%= _("advertise") %></th>
	    <th><%= _("renew date") %></th>
	    <th><%= _("show for days") %></th>
	    <th><%= _("cost") %></th>
	    <th></th>
	  </thead>
	  <tbody>
	    <% @renew_records.each do |renew| %>
	      <tr>
		<td><%= renew.created_at %></td>
		<td>#<%= renew.advertise.id %></td>
		<td><%= renew.renew_date %></td>
		<td><%= renew.show_for_days %></td>
		<td><%= renew.cost %></td>
		<td><%= link_to "",  delete_renew_advertise_path(renew.advertise_id, renew.id), method: :delete, data: { confirm: _('Are you sure?') }, class: del_btn_class, icons: del_btn_icon %></td>

	      </tr>
	    <% end %>
	  </tbody>
	</table>
      <% end %>

    </div>


  </div>
</section>

<section>
  <p class="title" data-section-title><a href="#panel-logs"><%= _("Logs") %></a></p>
  <div class="content" data-section-content>





    <div class="row">
      <% if @logs.exists? %>
	<h2><%= _("latest activities") %></h2>
	<table class="span12 table table-striped">
	  <thead>
	    <th><%= _("timestamp") %></th>
	    <th><%= _("advertise") %></th>
	    <th><%= _("activity") %></th>
	  </thead>
	  <tbody>
	    <% @logs.each do |log| %>
	      <tr>
		<td><%= log.created_at %></td>
		<% if log.logable -%>
		  <td>#<%= log.logable.id %></td>
		<% else %>
		  <td>-</td>
		<% end -%>

		<td><%= log.msg %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
      <% end %>
    </div>
</section>
</div>
</div>
</div>